### ISSUE TITLE
How to get User Access Token and User Access Token Secret

### ISSUE THREAD

**Issue by phuocantd** [Pythe1337N/garmin-connect#22]
I want to get User Access Token and User Access Token Secret when login garmin? any idea? thanks

**Comment by Pythe1337N** [comment]
That's not how this package is ment to work. It uses the regular web sign-in form and not some other form of authentication. You will need to store the username och password somehow since it's not token based.

**Comment by phuocantd** [comment]
I solved it

**Comment by samsouci** [comment]
@phuocantd Hey, I am keen to know how did you solve it please. I need to implement Oauth 1 Garmin authentication for my React Native App. Many thanks.

**Comment by phuocantd** [comment]
> @phuocantd Hey, I am keen to know how did you solve it please. I need to implement Oauth 1 Garmin authentication for my React Native App. Many thanks.

You can see an example here: https://github.com/phuocantd/react-native-garmin

**Comment by samsouci** [comment]
Thanks for he quick answer, I'll look into it :)

**Comment by evgeetha** [comment]
Hi
Don't use npm of react native garmin. It is not completed one.

**Comment by phuocantd** [comment]
> Hi Don't use npm of react native garmin. It is not completed one. To do oauth steps, you have to follow Oauth documents step1, step2, step3. After you registered and approved for Garmin access, you will get the document from Garmin team

yes, I using oauth 1.0

**Comment by mdswebgenerationz** [comment]
> Obrigado pela resposta rápida, vou dar uma olhada :)

Friend, were you able to complete the entire process of calling the Garmin APIs? I understood the context of the API's, but I can't execute even step 1, either in Javascript (through an AJAX request) or in PHP. Could you help me with this?
Thanks!

**Comment by phuocantd** [comment]
> > Obrigado pela resposta rápida, vou dar uma olhada :)
> 
> Friend, were you able to complete the entire process of calling the Garmin APIs? I understood the context of the API's, but I can't execute even step 1, either in Javascript (through an AJAX request) or in PHP. Could you help me with this? Thanks!

you can see my example
