### ISSUE TITLE
ARM Login Issue

### ISSUE THREAD

**Issue by tderflinger** [Pythe1337N/garmin-connect#67]
Hi,
Thanks a lot for your update of your library for the changed login.
On my Intel PC your solutions works great. But when I try it on the ARM platform on my Raspberry Pi, I get the following error when trying to login:

GarminConnect.js:105
            throw new Error('Missing credentials');

Have you ever tried it on the ARM platform?
Thanks!
-Thomas

**Comment by gregegan** [comment]
@tderflinger this likely is due to not having the garmin.config.json properly created

**Comment by tderflinger** [comment]
@gregegan, thanks for the hint. This did the trick, it works now!
